security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\CustomAuthenticator
                # enable_csrf: true  # CSRF protection is enabled by default
            logout:
                path: app_logout
            access_denied_handler: App\Security\AccessDeniedHandler
                #invalidate_session: true  # Sécurisation de la déconnexion
            # Handler pour les accès refusés (placé correctement ici)
            # access_denied_url: /access-denied  # OU une URL personnalisée

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    # Gestion des accès
    access_control:
        - { path: ^/insert, roles: ROLE_ADMIN }
        - { path: ^/update, roles: ROLE_ADMIN }
        - { path: ^/delete, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            App\Entity\User: 'auto'
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: 'auto'
                cost: 15