update:
    path: /update/{id}
    controller: App\Controller\AdminController::update

delete:
    path: /delete/{id}
    controller: App\Controller\AdminController::delete

admin_home:
    path: /admin
    controller: App\Controller\AdminController::adminHome

liste:
    path: /liste
    controller: App\Controller\ListeProduitsController::liste

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index: 
    path: /testroute 
    controller: App\Controller\TestController::index

home:
    path: /
    controller: App\Controller\HomeController::index

